#!/bin/bash
# gate: cheap
# Does every class ability a player can actually hold carry a description?
#
# WHAT HAPPENED. Upstream declared AbilInfo[] (inc/Creature.h:56,
# inc/Globals.h:243) and never defined it, so a class ability has always had a
# name (ClassAbilities[], src/Tables.cpp) and nowhere to carry prose. Phase 2
# of inc-nbjf pins WHICH abilities must be described and adds the ratchet that
# keeps the two name tables from drifting apart; phase 3 writes the
# descriptions themselves. This check reads source and two hand-maintained
# lists only -- no build, no game.
#
# THE TWO LISTS. tools/ability_descs.live names every ability that MUST carry
# a description: granted to a player somewhere in lib/, and named in live
# engine code outside the name tables (docs/specs/2026-09-20-ability-
# descriptions-spec.md, "Scope"). tools/ability_descs.exempt names every
# other ability that already has a ClassAbilities row -- almost all
# monster-only, granted through ABILITY() in lib/mon*.irh -- plus one
# delivery-mechanism constant, CA_GRANT_ITEM, that never gets a name row at
# all. Neither file is regenerated by this script: both are read as
# committed, and re-deriving the live set from lib/ and src/ is what
# assertion 4 is for.
#
# FOUR ASSERTIONS, all in tools/ability_descs_lib.py (imported, not shelled
# out to, so --selftest can exercise the same code paths the real run does):
#
#   1. Every ability in ability_descs.live has an AbilInfo row whose
#      description is non-empty.
#   2. Every AbilInfo row's name is character-for-character identical to
#      that ability's ClassAbilities name. The anti-drift assertion: two name
#      tables now exist (src/Tables.cpp) and nothing else stops them
#      diverging as either one is edited.
#   3. Every AbilInfo row names an ability that exists in ClassAbilities.
#   4. Every ability granted anywhere in lib/ (the nine player-facing files
#      the spec names) appears in ability_descs.live or ability_descs.exempt.
#      The ratchet: a newly granted ability fails this check until a human
#      decides which file it belongs in.
#
# WHAT THIS CANNOT CHECK: whether a description is ACCURATE. Assertion 1 only
# asks that the field be non-empty. A wrong description passes exactly as a
# right one does; only a human reading the ability's implementation catches
# that.
#
# Usage:
#   tools/check_ability_descs.sh              exit 0 pass, 1 fail, 2 could not measure
#   tools/check_ability_descs.sh --selftest    prove each assertion can fail
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT" || exit 2

command -v python3 >/dev/null || { echo "COULD NOT MEASURE: python3 missing"; exit 2; }

TABLES="src/Tables.cpp"
LIVE="tools/ability_descs.live"
EXEMPT="tools/ability_descs.exempt"

if [ "${1:-}" = "--selftest" ]; then
    exec python3 - "$ROOT" <<'PYEOF'
import re
import shutil
import sys
import tempfile
from pathlib import Path

root = Path(sys.argv[1])
sys.path.insert(0, str(root / "tools"))
import ability_descs_lib as lib  # noqa: E402

rc = 0


def report(name, ok, why=""):
    global rc
    if ok:
        print(f"selftest ok    {name}")
    else:
        print(f"selftest FAIL  {name}  {why}")
        rc = 1


def run(tables, live, exempt):
    return lib.run_all(tables, live, exempt, lib_root=root)


# Every mutation below targets ONLY the AbilInfo[] block, never
# ClassAbilities[] -- the two tables share id and name syntax closely enough
# (e.g. both open a row with "{ CA_X,") that a whole-file substring
# replacement can silently rewrite the wrong table. abilinfo_block() finds
# the same span parse_abil_info() parses, so a targeted replace inside it can
# only ever touch AbilInfo rows.
def abilinfo_block(text):
    start_re = re.compile(r"struct\s+AbilityInfoStruct\s+AbilInfo\[\]\s*=\s*\{")
    end_re = re.compile(r"\{\s*0\s*,\s*NULL\s*,\s*NULL\s*\}")
    m = start_re.search(text)
    if not m:
        raise ValueError("AbilInfo[] not found")
    e = end_re.search(text, m.end())
    if not e:
        raise ValueError("AbilInfo[] terminator not found")
    return m.end(), e.start()


def mutate_abilinfo(text, old, new, count=1):
    lo, hi = abilinfo_block(text)
    block = text[lo:hi]
    if old not in block:
        raise ValueError(f"{old!r} not found inside the AbilInfo[] block")
    return text[:lo] + block.replace(old, new, count) + text[hi:]


with tempfile.TemporaryDirectory(prefix="ability-descs-selftest-") as tmp:
    tmp = Path(tmp)

    # A clean copy of the source table this check reads. Mutating a COPY,
    # never the real tree, is the whole point: docs/VERIFICATION.md and this
    # project's history of oracles that could not fail both require it.
    tables = tmp / "Tables.cpp"
    shutil.copyfile(root / "src" / "Tables.cpp", tables)

    # This is phase 2 of inc-nbjf: AbilInfo[] carries only 4 rows today, and
    # tools/ability_descs.live names 96 abilities, so the REAL files do not
    # pass assertion 1 yet -- that gap is the ratchet working (phase 3 closes
    # it) and this selftest must not depend on it being closed. Build a
    # synthetic live/exempt split instead: the 4 abilities AbilInfo already
    # describes go in live_mini, and everything else the real two files
    # between them classify goes in exempt_mini. Together they classify
    # exactly what the real live+exempt classify, so assertion 4 still holds,
    # and live_mini asks only for descriptions that already exist, so
    # assertion 1 holds too. This is the "all four pass" control every
    # mutation below is measured against.
    described = {"CA_BERSERK_RAGE", "CA_DEVOURING", "CA_EVASION", "CA_INFRAVISION"}
    real_live = lib.read_name_list(root / "tools" / "ability_descs.live")
    real_exempt = lib.read_name_list(root / "tools" / "ability_descs.exempt")
    if not described <= real_live:
        report("phase-1 abilities are all in the real live list", False,
               f"missing: {sorted(described - real_live)}")

    live = tmp / "live_mini.txt"
    exempt = tmp / "exempt_mini.txt"
    live.write_text("\n".join(sorted(described)) + "\n")
    exempt.write_text(
        "\n".join(sorted(real_exempt | (real_live - described))) + "\n"
    )

    # Baseline: the unmutated copies must pass, or none of the four failures
    # below prove that the MUTATION caused the red result.
    ok, fails = run(tables, live, exempt)
    report("synthetic all-classified baseline passes", ok, "; ".join(fails[:3]))

    # --- assertion 1: a live ability's description goes empty -------------
    t1 = tmp / "Tables1.cpp"
    try:
        text = tables.read_text()
        entry_re = re.compile(
            r'\{\s*CA_DEVOURING\s*,\s*"Devouring"\s*,'
            r'\s*(?:"(?:\\.|[^"\\])*"\s*)+\}',
            re.DOTALL,
        )
        lo, hi = abilinfo_block(text)
        block, n = entry_re.subn('{ CA_DEVOURING, "Devouring", "" }', text[lo:hi])
        if n != 1:
            raise ValueError(f"replaced {n} occurrence(s) of CA_DEVOURING's row, wanted 1")
        t1.write_text(text[:lo] + block + text[hi:])
    except ValueError as e:
        report("assertion 1 setup found CA_DEVOURING's row", False, str(e))
    else:
        ok1, fails1 = run(t1, live, exempt)
        got = any("FAIL[1]: CA_DEVOURING" in f for f in fails1)
        report("assertion 1 (empty description) goes red", (not ok1) and got,
               f"fails={fails1[:3]}")

    # --- assertion 2: an AbilInfo name disagrees with ClassAbilities -------
    t2 = tmp / "Tables2.cpp"
    mutated = mutate_abilinfo(
        tables.read_text(),
        '{ CA_EVASION, "Evasion",', '{ CA_EVASION, "Evasive Action",'
    )
    t2.write_text(mutated)
    ok2, fails2 = run(t2, live, exempt)
    got = any("FAIL[2]: CA_EVASION" in f for f in fails2)
    report("assertion 2 (name drift) goes red", (not ok2) and got, f"fails={fails2[:3]}")

    # --- assertion 3: an AbilInfo row names something ClassAbilities lacks -
    # The replacement includes the quoted name, not just "{ CA_INFRAVISION,",
    # because ClassAbilities[] ALSO opens a row with that shorter prefix and
    # mutate_abilinfo's own block restriction is the belt; this is the braces.
    t3 = tmp / "Tables3.cpp"
    mutated = mutate_abilinfo(
        tables.read_text(),
        '{ CA_INFRAVISION, "Infravision",', '{ CA_NO_SUCH_ABILITY, "Infravision",'
    )
    t3.write_text(mutated)
    ok3, fails3 = run(t3, live, exempt)
    got = any("FAIL[3]: CA_NO_SUCH_ABILITY" in f for f in fails3)
    report("assertion 3 (unknown ability) goes red", (not ok3) and got, f"fails={fails3[:3]}")

    # --- assertion 4: a granted ability appears in neither list ------------
    # CA_DEVOURING is genuinely granted in lib/ (real files, not mutated).
    # Drop it from both list copies and it must be reported as unclassified.
    live4 = tmp / "live4.txt"
    exempt4 = tmp / "exempt4.txt"
    live4.write_text(
        "\n".join(ln for ln in live.read_text().splitlines()
                   if ln.strip() != "CA_DEVOURING") + "\n"
    )
    exempt4.write_text(exempt.read_text())
    ok4, fails4 = run(tables, live4, exempt4)
    got = any("FAIL[4]: CA_DEVOURING" in f for f in fails4)
    report("assertion 4 (unclassified grant) goes red", (not ok4) and got,
           f"fails={fails4[:3]}")

    # And the real, unmutated tree end to end, via the actual entry point --
    # not just the library -- so a wiring mistake in the wrapper is caught too.
    print()
    print("selftest: pass" if rc == 0 else "selftest: FAIL")
sys.exit(rc)
PYEOF
fi

RESULT="$(python3 - "$ROOT" "$TABLES" "$LIVE" "$EXEMPT" <<'PYEOF'
import sys
from pathlib import Path

root, tables, live, exempt = sys.argv[1:5]
sys.path.insert(0, str(Path(root) / "tools"))
import ability_descs_lib as lib  # noqa: E402

ok, fails = lib.run_all(tables, live, exempt, lib_root=Path(root))
for f in fails:
    print(f)
print("PASS" if ok else "FAIL", len(fails))
PYEOF
)"
rc=$?

echo "$RESULT" | sed '$d'
last="$(echo "$RESULT" | tail -1)"

if [ "$rc" -ne 0 ]; then
    echo "COULD NOT MEASURE: ability_descs_lib.py raised an error"
    exit 2
fi

case "$last" in
    "PASS "*)
        echo "PASS: every assertion holds ($LIVE, $EXEMPT, $TABLES agree)"
        exit 0
        ;;
    "FAIL "*)
        n="${last#FAIL }"
        echo "FAIL: $n assertion failure(s) above"
        exit 1
        ;;
    *)
        echo "COULD NOT MEASURE: unreadable output from ability_descs_lib.py"
        echo "$RESULT"
        exit 2
        ;;
esac
